### ISSUE TITLE
Wann kommt Release 1.0?

### ISSUE THREAD

**Issue by LMStudent** [LernMoment/einstieg-csharp-syntax#1]
Hallo @suchja, kannst du mir sagen, wann das offizielle Release 1.0 erscheint?

**Comment by suchja** [comment]
Das wird spätestens morgen erscheinen. Ich habe es bereits fertig, aber ich muss es noch auf GitHub veröffentlichen. Ich lasse dieses Issue offen, bis ich es erledigt habe.

**Comment by LMStudent** [comment]
@suchja habe dieses Issue für das falsche Repository erstellt! Werde es jetzt schließen.
