### ISSUE TITLE
For-Schleife

### ISSUE THREAD

**Issue by LMStudent** [LernMoment/einstieg-csharp-syntax#2]
Hast du schon etwas für die "For-Schleife" vorbereitet? Da könnte ich etwas behilflich sein.

**Comment by suchja** [comment]
@LMStudent Da habe ich noch nichts vorbereitet und wäre super dankbar, wenn du dich einbringen würdest.

**Comment by LMStudent** [comment]
Gibt es eine Vorlage oder sonstige Punkte die ich beachten muss?

**Comment by suchja** [comment]
Nein! Es wäre gut, wenn du eine Methode `static void Beschreibung()` wie bei der [While-Schleife](https://github.com/LernMoment/einstieg-csharp-syntax/blob/master/WhileSchleife/Einfuehrung.cs) verwendest in der du die Beschreibung erstellst. Ansonsten kannst du dich am Aufbau des [Projektes für die while-Schleife](https://github.com/LernMoment/einstieg-csharp-syntax/tree/master/WhileSchleife) orientieren, aber es auch anpassen.
